---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

driver:
  name: default

platforms:
  - name: proxmox-test
    image: debian:12
    pre_build_image: true
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      gathering: smart
      fact_caching: jsonfile
      fact_caching_connection: /tmp/facts
  inventory:
    group_vars:
      all:
        # Override defaults for testing environment
        zfs_swap_size: "1G"
        common_packages:
          - htop
          - iotop

verifier:
  name: ansible
